version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ""
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: default_laravel
      DB_USERNAME: admin
      DB_PASSWORD: admin

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  node:
    image: node:18
    container_name: vite-frontend
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    ports:
      - "5175:5175"
    command: ["npm", "run", "dev"]

volumes:
  dbdata:

networks:
  laravel:
